@baseUrl = http://localhost:3000
@id = 7a4384b6-63cf-4264-bdec-9ab4c29d9582
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJkNDlkYmRkLTNiOTAtNGU4Yi05ZGQ0LTRlZWQ3Y2EzMjY2ZiIsIm5vbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obkBleGFtcGxlLmNvbSIsImlhdCI6MTc0MzE2ODI2NywiZXhwIjoxNzQzNzczMDY3LCJhdWQiOiJ1c2VycyIsImlzcyI6ImxvZ2luIiwic3ViIjoiMmQ0OWRiZGQtM2I5MC00ZThiLTlkZDQtNGVlZDdjYTMyNjZmIn0.n6YPOyYulaQtvNjwTHDovdqu--HFCUAFueeHYGlUpgE
###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "john@example.com",
    "senha": "password123"
}

###
POST {{baseUrl}}/auth/register

###
POST {{baseUrl}}/auth/forget 

###
POST {{baseUrl}}/auth/reset

###
POST {{baseUrl}}/auth/verify
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/auth/verify
Authorization: Bearer ""

###
POST {{baseUrl}}/auth/amem
Authorization: Bearer {{token}}
